version: '3'

volumes:
  mysql_volume:
    driver: 'local'

services:
  db:
    image: mysql:5.7.11
    command: >
      mysqld
          --character-set-server=utf8
          --collation-server=utf8_unicode_ci
          --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_volume:/var/lib/mysql:delegated

  db_test:
    image: mysql:5.7.11
    command: >
      mysqld
          --character-set-server=utf8
          --collation-server=utf8_unicode_ci
          --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_test
      MYSQL_USER: laravel_test
      MYSQL_PASSWORD: laravel_test

  laravel_php:
    build: ./docker/php
    volumes:
      - ./www:/var/www
    depends_on:
      - db


  laravel_nginx:
    image: nginx:latest
    ports:
      - "7070:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    depends_on:
      - db
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "7079:80"
    depends_on:
      - db
